use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

fn main() {
    println!("cargo:rerun-if-env-changed=FITZ_EMBED_UI_DIR");

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));

    let asset_dirs = resolve_asset_dirs(&manifest_dir);
    let output_path = out_dir.join("embedded_assets.rs");

    if let Err(error) = write_embedded_asset_source(&output_path, &asset_dirs) {
        panic!("failed to generate embedded admin UI asset source: {error}");
    }
}

fn resolve_asset_dirs(manifest_dir: &Path) -> Vec<PathBuf> {
    let env_candidate = env::var_os("FITZ_EMBED_UI_DIR").map(PathBuf::from);
    let ui_dist = manifest_dir.join("ui").join("dist");
    let public_dir = manifest_dir.join("public");

    if let Some(candidate) = env_candidate {
        if candidate.join("index.html").is_file() {
            println!("cargo:rerun-if-changed={}", candidate.display());
            return vec![candidate];
        }
    }

    let mut asset_dirs = Vec::new();

    if ui_dist.join("index.html").is_file() {
        println!("cargo:rerun-if-changed={}", ui_dist.display());
        asset_dirs.push(ui_dist);
    }

    if public_dir.join("index.html").is_file() {
        println!("cargo:rerun-if-changed={}", public_dir.display());
        asset_dirs.push(public_dir);
    }

    if asset_dirs.is_empty() {
        println!(
            "cargo:warning=No admin UI asset directory found; embedded admin UI will be unavailable until FITZ_EMBED_UI_DIR, ui/dist, or public/index.html exists"
        );
    }

    asset_dirs
}

fn write_embedded_asset_source(output_path: &Path, asset_dirs: &[PathBuf]) -> io::Result<()> {
    let mut output = File::create(output_path)?;
    writeln!(output, "// @generated by build.rs")?;

    match asset_dirs.is_empty() {
        false => {
            let assets = collect_assets(asset_dirs)?;
            writeln!(
                output,
                "static EMBEDDED_ASSET_SOURCES: &[EmbeddedAssetSource] = &["
            )?;

            for (relative_path, absolute_path) in assets {
                writeln!(
                    output,
                    "    EmbeddedAssetSource::new({relative_path:?}, include_bytes!(r#\"{}\"#) as &[u8]),",
                    normalize_path(&absolute_path)
                )?;
            }

            writeln!(output, "];")?;
        }
        true => {
            writeln!(
                output,
                "static EMBEDDED_ASSET_SOURCES: &[EmbeddedAssetSource] = &[];"
            )?;
        }
    }

    Ok(())
}

fn collect_assets(asset_dirs: &[PathBuf]) -> io::Result<Vec<(String, PathBuf)>> {
    let mut assets = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for asset_dir in asset_dirs {
        for entry in WalkDir::new(asset_dir).into_iter().filter_map(Result::ok) {
            if !entry.file_type().is_file() {
                continue;
            }

            let relative_path = entry
                .path()
                .strip_prefix(asset_dir)
                .expect("asset must be inside the selected asset directory")
                .to_string_lossy()
                .replace('\\', "/");

            if !seen.insert(relative_path.clone()) {
                continue;
            }

            let absolute_path = fs::canonicalize(entry.path())?;
            println!("cargo:rerun-if-changed={}", entry.path().display());
            assets.push((relative_path, absolute_path));
        }
    }

    assets.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(assets)
}

fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
