use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

fn main() {
    println!("cargo:rerun-if-env-changed=FITZ_EMBED_UI_DIR");

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));

    let asset_dir = resolve_asset_dir(&manifest_dir);
    let output_path = out_dir.join("embedded_assets.rs");

    if let Err(error) = write_embedded_asset_source(&output_path, asset_dir.as_deref()) {
        panic!("failed to generate embedded admin UI asset source: {error}");
    }
}

fn resolve_asset_dir(manifest_dir: &Path) -> Option<PathBuf> {
    let env_candidate = env::var_os("FITZ_EMBED_UI_DIR").map(PathBuf::from);
    let ui_dist = manifest_dir.join("ui").join("dist");
    let public_dir = manifest_dir.join("public");

    for candidate in [env_candidate, Some(ui_dist), Some(public_dir)]
        .into_iter()
        .flatten()
    {
        if candidate.join("index.html").is_file() {
            println!("cargo:rerun-if-changed={}", candidate.display());
            return Some(candidate);
        }
    }

    println!(
        "cargo:warning=No admin UI asset directory found; embedded admin UI will be unavailable until FITZ_EMBED_UI_DIR, ui/dist, or public/index.html exists"
    );
    None
}

fn write_embedded_asset_source(output_path: &Path, asset_dir: Option<&Path>) -> io::Result<()> {
    let mut output = File::create(output_path)?;
    writeln!(output, "// @generated by build.rs")?;

    match asset_dir {
        Some(asset_dir) => {
            let assets = collect_assets(asset_dir)?;
            writeln!(
                output,
                "static EMBEDDED_ASSET_SOURCES: &[EmbeddedAssetSource] = &["
            )?;

            for (relative_path, absolute_path) in assets {
                writeln!(
                    output,
                    "    EmbeddedAssetSource::new({relative_path:?}, include_bytes!(r#\"{}\"#) as &[u8]),",
                    normalize_path(&absolute_path)
                )?;
            }

            writeln!(output, "];")?;
        }
        None => {
            writeln!(
                output,
                "static EMBEDDED_ASSET_SOURCES: &[EmbeddedAssetSource] = &[];"
            )?;
        }
    }

    Ok(())
}

fn collect_assets(asset_dir: &Path) -> io::Result<Vec<(String, PathBuf)>> {
    let mut assets = Vec::new();

    for entry in WalkDir::new(asset_dir).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }

        let relative_path = entry
            .path()
            .strip_prefix(asset_dir)
            .expect("asset must be inside the selected asset directory")
            .to_string_lossy()
            .replace('\\', "/");
        let absolute_path = fs::canonicalize(entry.path())?;

        println!("cargo:rerun-if-changed={}", entry.path().display());
        assets.push((relative_path, absolute_path));
    }

    assets.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(assets)
}

fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
