// Auto-generated by fetch-gen
import type { FetchClient, FetchResponse } from "@fgrzl/fetch";
import { buildQueryParams } from "@fgrzl/fetch";

/**
 * Creates an API adapter with typed methods for all OpenAPI operations.
 *
 * @param client - The FetchClient instance to use for HTTP requests
 * @returns An object with typed methods for each API operation
 *
 * @example
 * ```typescript
 * import { createAdapter } from './generated';
 * import client from '@fgrzl/fetch';
 *
 * client.setBaseUrl('https://api.example.com');
 * const api = createAdapter(client);
 *
 * const response = await api.getUsers();
 * if (response.ok) {
 *   console.log(response.data);
 * }
 * ```
 */
export function createAdapter(client: FetchClient): {
  /**
   * Get KV domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<KvStats>
   */
  getKvStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<KvStats>>;
  /**
   * Get Lease domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<LeaseStats>
   */
  getLeaseStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<LeaseStats>>;
  /**
   * Get Notice domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<NoticeStats>
   */
  getNoticeStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<NoticeStats>>;
  /**
   * Get Queue domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<QueueStats>
   */
  getQueueStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<QueueStats>>;
  /**
   * Get RPC domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<RpcStats>
   */
  getRpcStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<RpcStats>>;
  /**
   * Get Schedule domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ScheduleStats>
   */
  getScheduleStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<ScheduleStats>>;
  /**
   * Create admin session
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
  createAdminSession: (
    body: LoginRequest,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string },
  ) => Promise<FetchResponse<boolean>>;
  /**
   * Delete admin session
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
  deleteAdminSession: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<boolean>>;
  /**
   * Get current admin session
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SessionResponse>
   */
  getAdminSession: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<SessionResponse>>;
  /**
   * List active sessions
   *
   * @param query - Query parameters
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SessionsList>
   */
  listActiveSessions: (
    query?: { realm?: string },
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string },
  ) => Promise<FetchResponse<SessionsList>>;
  /**
   * Get global broker and domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<GlobalStats>
   */
  getGlobalStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<GlobalStats>>;
  /**
   * Get Stream domain statistics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<StreamStats>
   */
  getStreamStats: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<StreamStats>>;
  /**
   * Legacy health endpoint
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<HealthStatus>
   */
  getLegacyHealth: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<HealthStatus>>;
  /**
   * Liveness probe
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<HealthStatus>
   */
  getLivenessProbe: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<HealthStatus>>;
  /**
   * Prometheus metrics
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<any>
   */
  getMetrics: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<any>>;
  /**
   * Readiness probe
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ReadyStatus>
   */
  getReadinessProbe: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<ReadyStatus>>;
  /**
   * Startup probe
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<StartupStatus>
   */
  getStartupProbe: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<StartupStatus>>;
} {
  return {
    getKvStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<KvStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getKvStats" };
      return client.get(`/api/v1/kv/stats`, undefined, finalOptions);
    },
    getLeaseStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<LeaseStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getLeaseStats" };
      return client.get(`/api/v1/lease/stats`, undefined, finalOptions);
    },
    getNoticeStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<NoticeStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getNoticeStats" };
      return client.get(`/api/v1/notice/stats`, undefined, finalOptions);
    },
    getQueueStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<QueueStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getQueueStats" };
      return client.get(`/api/v1/queue/stats`, undefined, finalOptions);
    },
    getRpcStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<RpcStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getRpcStats" };
      return client.get(`/api/v1/rpc/stats`, undefined, finalOptions);
    },
    getScheduleStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<ScheduleStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getScheduleStats" };
      return client.get(`/api/v1/schedule/stats`, undefined, finalOptions);
    },
    createAdminSession: (
      body: LoginRequest,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string },
    ): Promise<FetchResponse<boolean>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? "createAdminSession",
      };
      return client.post(`/api/v1/session`, body, undefined, finalOptions);
    },
    deleteAdminSession: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<boolean>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? "deleteAdminSession",
      };
      return client.del(`/api/v1/session`, undefined, finalOptions);
    },
    getAdminSession: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<SessionResponse>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getAdminSession" };
      return client.get(`/api/v1/session`, undefined, finalOptions);
    },
    listActiveSessions: (
      query?: { realm?: string },
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string },
    ): Promise<FetchResponse<SessionsList>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? "listActiveSessions",
      };
      const queryString = query ? buildQueryParams(query) : "";
      const url = `/api/v1/sessions` + (queryString ? "?" + queryString : "");
      return client.get(url, undefined, finalOptions);
    },
    getGlobalStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<GlobalStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getGlobalStats" };
      return client.get(`/api/v1/stats`, undefined, finalOptions);
    },
    getStreamStats: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<StreamStats>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getStreamStats" };
      return client.get(`/api/v1/stream/stats`, undefined, finalOptions);
    },
    getLegacyHealth: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<HealthStatus>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getLegacyHealth" };
      return client.get(`/health`, undefined, finalOptions);
    },
    getLivenessProbe: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<HealthStatus>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getLivenessProbe" };
      return client.get(`/healthz`, undefined, finalOptions);
    },
    getMetrics: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<any>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getMetrics" };
      return client.get(`/metrics`, undefined, finalOptions);
    },
    getReadinessProbe: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<ReadyStatus>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getReadinessProbe" };
      return client.get(`/readyz`, undefined, finalOptions);
    },
    getStartupProbe: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<StartupStatus>> => {
      const finalOptions = { ...options, operationId: options?.operationId ?? "getStartupProbe" };
      return client.get(`/startupz`, undefined, finalOptions);
    },
  };
}

/** AreaCollection schema */
export interface AreaCollection {
  areas: Array<AreaEntry>;
  realm: string;
}

/** AreaDetail schema */
export interface AreaDetail {
  area: string;
  realm: string;
}

/** AreaEntry schema */
export interface AreaEntry {
  area: string;
}

/** BrokerStats schema */
export interface BrokerStats {
  connections: number;
  messages_per_second: number;
  realms: Array<string>;
  sessions: number;
  uptime_seconds: number;
}

/** DomainStats schema */
export interface DomainStats {
  kv: KvStats;
  lease: LeaseStats;
  notice: NoticeStats;
  queue: QueueStats;
  rpc: RpcStats;
  schedule: ScheduleStats;
  stream: StreamStats;
}

/** Error schema */
export interface Error {
  error: string;
}

/** GlobalStats schema */
export interface GlobalStats {
  broker: BrokerStats;
  domains: DomainStats;
}

/** HealthStatus schema */
export interface HealthStatus {
  status: string;
}

/** Durable KV committed data exists separately from this admin view. This resource detail describes only the current broker process's live in-memory transaction activity for the resource. `transactions_active` counts active session-scoped transactions and resets after disconnect cleanup or broker restart. */
export interface KvResourceDetail {
  area: string;
  realm: string;
  resource: string;
  /** Broker-local count of active in-memory KV transactions for this resource. This is not a durable recovery handle and resets on disconnect cleanup or broker restart. */
  transactions_active: number;
}

/** KvStats schema */
export interface KvStats {
  keys_total: number;
  operations_per_second: number;
  transactions_active: number;
}

/** Session-scoped active KV transaction snapshot on the current broker process. Open transactions disappear on disconnect or broker restart and do not represent durable recovery state. Committed-data durability is handled separately by storage commit semantics. */
export interface KvTransaction {
  area?: string;
  idle_seconds?: number;
  mode?: string;
  operations_count?: number;
  realm?: string;
  resource?: string;
  started_at?: string;
  tx_id?: number;
}

/** KvTransactionsList schema */
export interface KvTransactionsList {
  transactions: Array<KvTransaction>;
}

/** Point-in-time live in-memory Lease state for a single resource on the current broker process. Counts reset on disconnect cleanup or broker restart and do not imply durable recovery. */
export interface LeaseResourceDetail {
  active_leases: number;
  area: string;
  realm: string;
  resource: string;
}

/** LeaseStats schema */
export interface LeaseStats {
  leases_active: number;
  operations_per_second: number;
}

/** LoginRequest schema */
export interface LoginRequest {
  password: string;
  username: string;
}

/** Live in-memory Notice detail for the current broker process. `subscriptions_active` is session-scoped fanout state only and disappears on disconnect cleanup or broker restart. */
export interface NoticeResourceDetail {
  area: string;
  realm: string;
  resource: string;
  /** Broker-local count of active Notice subscriptions for this resource. Not durable and not replayable. */
  subscriptions_active: number;
}

/** NoticeStats schema */
export interface NoticeStats {
  publishes_per_second: number;
  subscriptions_active: number;
}

/** Live in-memory Notice subscription state for the current broker process. Subscriptions are session-scoped and are removed on disconnect or broker restart. */
export interface NoticeSubscription {
  /** Timestamp when this live in-memory subscription was created. Resets after reconnect or broker restart. */
  created_at?: string;
  /** Live counter of notifications delivered to this current in-memory subscription. Not durable and resets after reconnect or broker restart. */
  notifications_received?: number;
  /** Exact route or wildcard pattern tracked in memory for the active session. */
  pattern?: string;
  /** Realm extracted from the current subscription pattern. */
  realm?: string;
  /** Owning live session identifier. The subscription disappears when this session disconnects. */
  session_id?: string;
  /** Broker-local identifier for the currently active in-memory subscription. */
  subscription_id?: number;
}

/** NoticeSubscriptionsList schema */
export interface NoticeSubscriptionsList {
  subscriptions: Array<NoticeSubscription>;
}

/** OperationCollection schema */
export interface OperationCollection {
  area: string;
  operations: Array<OperationEntry>;
  realm: string;
  resource: string;
}

/** OperationEntry schema */
export interface OperationEntry {
  operation: string;
}

/** Live in-memory Queue dead-letter snapshot for the current broker process. Dead-letter rows remain durably stored, but this endpoint only reflects rows for queue actors that are currently warm on this broker. */
export interface QueueDeadLetter {
  area: string;
  attempts: number;
  dead_lettered_at: string;
  family: number;
  message_id: number;
  realm: string;
  reason: string;
  resource: string;
}

/** QueueDeadLettersList schema */
export interface QueueDeadLettersList {
  messages: Array<QueueDeadLetter>;
}

/** Live in-memory Queue inflight entry for the current broker process only. `inflight_token` and `session_id` belong to one active inflight entry and are dropped on disconnect cleanup, idle actor eviction, or broker restart. */
export interface QueueInflight {
  area: string;
  attempts: number;
  expires_at: string;
  family: number;
  inflight_token: string;
  message_id: number;
  realm: string;
  resource: string;
  session_id: string;
}

/** QueueInflightList schema */
export interface QueueInflightList {
  inflight: Array<QueueInflight>;
}

/** Point-in-time Queue resource detail for the current broker process. Counts describe only the queue actor state currently warm in memory and do not represent a durable inventory of every committed queue in storage. */
export interface QueueResourceDetail {
  area: string;
  messages_dead_lettered: number;
  messages_delayed: number;
  messages_inflight: number;
  messages_ready: number;
  messages_total: number;
  oldest_message_age_seconds: number;
  realm: string;
  resource: string;
}

/** QueueStats schema */
export interface QueueStats {
  inflight_active: number;
  messages_dead_lettered: number;
  messages_delayed: number;
  messages_pending: number;
  messages_ready: number;
  operations_per_second: number;
}

/** ReadyStatus schema */
export interface ReadyStatus {
  checks: Record<string, string>;
  status: string;
}

/** RealmCollection schema */
export interface RealmCollection {
  realms: Array<RealmEntry>;
}

/** RealmDetail schema */
export interface RealmDetail {
  realm: string;
}

/** RealmEntry schema */
export interface RealmEntry {
  realm: string;
}

/** ResourceCollection schema */
export interface ResourceCollection {
  area: string;
  realm: string;
  resources: Array<ResourceEntry>;
}

/** ResourceEntry schema */
export interface ResourceEntry {
  resource: string;
}

/** Point-in-time live in-memory RPC state for a single operation on the current broker process. Worker registrations and pending requests are ephemeral, reset on disconnect cleanup or broker restart, and do not represent durable backlog or recovery state. */
export interface RpcOperationDetail {
  area: string;
  operation: string;
  realm: string;
  /** Live in-memory pending requests waiting for a worker on this broker process. Not durable across disconnect or restart. */
  requests_pending: number;
  resource: string;
  /** Live in-memory workers currently registered for this exact operation on this broker process. */
  workers_registered: number;
}

/** RpcPendingList schema */
export interface RpcPendingList {
  requests: Array<RpcPendingRequest>;
}

/** Live in-memory pending RPC request tracked by the current broker process only. Pending requests disappear on timeout, cleanup, or broker restart. */
export interface RpcPendingRequest {
  /** Approximate wall-clock age of the current in-memory pending request. */
  age_seconds?: number;
  /** Correlation identifier for the live in-memory request. */
  correlation_id?: string;
  /** Exact RPC operation route for the currently pending request. */
  route?: string;
  /** Timestamp when the current broker process accepted and tracked the request in memory. */
  submitted_at?: string;
  /** Broker-local worker session currently assigned to the pending request when one is known. */
  worker_session_id?: string | null;
}

/** RpcStats schema */
export interface RpcStats {
  operations_per_second: number;
  requests_pending: number;
  workers_registered: number;
}

/** Live in-memory RPC worker registration for the current broker process. Workers must re-register after disconnect or broker restart. */
export interface RpcWorker {
  /** Average end-to-end latency for terminal RPC requests completed by this live worker registration in the current broker process. */
  average_latency_ms?: number;
  /** Realm extracted from the registered RPC route. */
  realm?: string;
  /** Timestamp when this live worker registration was created. Resets after disconnect or broker restart. */
  registered_at?: string;
  /** Number of terminal RPC requests completed by this live worker registration in the current broker process. */
  requests_handled?: number;
  /** Exact RPC operation route currently handled by this live worker registration. */
  route?: string;
  /** Broker-local worker session identifier for the active registration. */
  session_id?: string;
}

/** RpcWorkersList schema */
export interface RpcWorkersList {
  workers: Array<RpcWorker>;
}

/** Durable, boot-loaded schedule definition detail for the current broker. This describes persisted timing intent, not durable subscriber delivery or durable execution history. `executions_total` remains a non-authoritative placeholder until durable execution history exists. */
export interface ScheduleResourceDetail {
  area: string;
  cron?: string | null;
  enabled: boolean;
  /** Non-authoritative current broker counter. This is not durable execution history. */
  executions_total: number;
  next_run?: string | null;
  realm: string;
  resource: string;
}

/** ScheduleStats schema */
export interface ScheduleStats {
  ack_failures_total: number;
  executions_per_minute: number;
  notify_failures_total: number;
  overdue_normalizations_total: number;
  pending_fire_claims: number;
  schedules_active: number;
  subscriptions_active: number;
}

/** SessionInfo schema */
export interface SessionInfo {
  connected_at?: string;
  idle_seconds?: number;
  messages_received?: number;
  messages_sent?: number;
  realm?: string;
  remote_addr?: string;
  session_id?: string;
  transport?: string;
}

/** SessionResponse schema */
export interface SessionResponse {
  authenticated: boolean;
  username: string;
}

/** SessionsList schema */
export interface SessionsList {
  sessions: Array<SessionInfo>;
}

/** StartupStatus schema */
export interface StartupStatus {
  startup_time_seconds: number;
  status: string;
}

/** StreamAreaWatermark schema */
export interface StreamAreaWatermark {
  family: number;
  watermark: number;
}

/** StreamAreaWatermarkDetail schema */
export interface StreamAreaWatermarkDetail {
  area: string;
  family_watermarks: Array<StreamAreaWatermark>;
  realm: string;
  resource_count: number;
}

/** StreamRealmWatermark schema */
export interface StreamRealmWatermark {
  family: number;
  watermark: number;
}

/** StreamRealmWatermarkDetail schema */
export interface StreamRealmWatermarkDetail {
  area_count: number;
  family_watermarks: Array<StreamRealmWatermark>;
  realm: string;
  resource_count: number;
}

/** Durable committed stream metadata for one resource plus the current broker process's live append-session count. `offset`, `watermark`, and `size_bytes` survive restart; `sessions_active` is ephemeral and resets on disconnect cleanup or broker restart. */
export interface StreamResourceDetail {
  area: string;
  offset: number;
  realm: string;
  resource: string;
  sessions_active: number;
  size_bytes: number;
  watermark: number;
}

/** StreamStats schema */
export interface StreamStats {
  events_total: number;
  operations_per_second: number;
  streams_active: number;
  subscriptions_active: number;
}
