//! Queue protocol message types and responses
//!
//! Defines the message types for queue operations:
//! - **Send**: Add message to queue
//! - **Receive**: Lease one or more messages for processing
//! - **Extend**: Extend lease expiration for a received message
//! - **Ack**: Acknowledge and delete message
//!
//! # Queue Identity
//!
//! Queues are uniquely identified by (RouteFamily, realm, area, resource):
//! - RouteFamily: Routing isolation boundary (opaque u64)
//! - realm/area/resource: Logical identity within the family
//!
//! # Lease Semantics
//!
//! - Messages are received with a lease duration
//! - While leased, messages are invisible to other consumers
//! - Leases expire automatically, returning messages to the ready queue
//! - Redelivered messages have incremented attempt counters
//!
//! # Token Protocol
//!
//! - Each received message gets a random u64 token
//! - Tokens must be provided for extend/ack operations
//! - Invalid tokens are rejected (prevents accidental duplicate operations)
//! - Tokens are ephemeral (not persisted, regenerated on actor restart)
//!
//! # Long Polling (RPC-Level Only)
//!
//! Receive operations support optional long polling via `wait_seconds`:
//! - QueueActor always returns immediately (never blocks)
//! - If empty and `wait_seconds > 0`, RPC layer:
//!   1. Subscribes to `notice://{realm}/{area}/{resource}/available`
//!   2. Waits up to `wait_seconds` for a notice or timeout
//!   3. Retries receive on notice or timeout
//! - Notices are hints (at-most-once), not guarantees
//! - QueueActor never stores waiters or blocking state

use crate::runtime::routing::{Route, RouteFamily};
use bytes::Bytes;
use serde::{Deserialize, Serialize};

/// Parsed queue identity
///
/// Queues are uniquely identified by (RouteFamily, realm, area, resource):
/// - RouteFamily: Routing isolation boundary (opaque u64)
/// - realm/area/resource: Logical identity within the family
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct QueueKey {
    pub family: RouteFamily,
    pub realm: String,
    pub area: String,
    pub resource: String,
}

impl QueueKey {
    /// Parse a route into queue key
    ///
    /// Expected route format: `{scheme}://{realm}/{area}/{resource}/{operation}`
    /// or `/{realm}/{area}/{resource}/{operation}`
    ///
    /// Returns None if the route doesn't match the expected format.
    pub fn from_route(family: RouteFamily, route: &Route) -> Option<Self> {
        let path = route.as_str();

        // Strip scheme if present (e.g., "queue://..." → "...")
        let path_without_scheme = if let Some(pos) = path.find("://") {
            &path[pos + 3..]
        } else {
            path
        };

        let mut parts = path_without_scheme.trim_start_matches('/').split('/');
        let realm = parts.next()?;
        let area = parts.next()?;
        let resource = parts.next()?;

        // Accept both 3-segment (realm/area/resource) and 4+ segment (realm/area/resource/...) for queue identity
        if !realm.is_empty() && !area.is_empty() && !resource.is_empty() {
            Some(QueueKey {
                family,
                realm: realm.to_string(),
                area: area.to_string(),
                resource: resource.to_string(),
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::routing::Route;

    #[test]
    fn should_parse_queue_route_with_scheme() {
        // Arrange
        let route = Route::new("queue://acme/tasks/work");
        let family = RouteFamily::new(1);

        // Act
        let key = QueueKey::from_route(family, &route);

        // Assert
        assert!(key.is_some());
        let key = key.unwrap();
        assert_eq!(key.realm, "acme");
        assert_eq!(key.area, "tasks");
        assert_eq!(key.resource, "work");
    }

    #[test]
    fn should_parse_queue_route_without_scheme() {
        // Arrange
        let route = Route::new("acme/tasks/work");
        let family = RouteFamily::new(2);

        // Act
        let key = QueueKey::from_route(family, &route);

        // Assert
        assert!(key.is_some());
        let key = key.unwrap();
        assert_eq!(key.realm, "acme");
        assert_eq!(key.area, "tasks");
        assert_eq!(key.resource, "work");
    }

    #[test]
    fn should_reject_queue_route_with_too_few_segments() {
        // Arrange
        let route = Route::new("queue://acme/tasks");
        let family = RouteFamily::new(1);

        // Act
        let key = QueueKey::from_route(family, &route);

        // Assert
        assert!(key.is_none());
    }
}

/// Message identifier
///
/// Opaque u64 identifier for messages in the queue.
/// Generated by the actor and used for all subsequent operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MessageId(u64);

impl MessageId {
    /// Create a new message ID from a u64
    pub fn new(id: u64) -> Self {
        Self(id)
    }

    /// Get the underlying u64 value
    pub fn as_u64(&self) -> u64 {
        self.0
    }
}

impl std::fmt::Display for MessageId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Reserved message with body and lease metadata
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReservedMessage {
    /// Message identifier
    pub id: MessageId,

    /// Message body
    pub body: Bytes,

    /// Lease token (required for extend/complete)
    pub token: u64,

    /// Lease duration in seconds
    pub lease_seconds: u64,

    /// Number of delivery attempts (starts at 1)
    pub attempts: u32,
}

/// Queue domain messages
///
/// All queue operations are asynchronous and return responses via
/// the actor messaging system.
#[derive(Debug, Clone)]
pub enum QueueMessage {
    /// Send a message to the queue
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/send`
    ///
    /// Writes the message body to durable storage and adds it to the ready queue.
    /// If delay_seconds is provided, message won't be visible until delay elapses.
    /// Returns the MessageId for tracking.
    Send {
        family_id: RouteFamily,
        route: Route,
        body: Bytes,
        delay_seconds: Option<u64>,
    },

    /// Receive messages for processing
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/receive`
    ///
    /// Pops up to `batch_size` messages from the ready queue, creates leases,
    /// and returns them with bodies loaded from storage.
    ///
    /// If `batch_size` is None, defaults to 1.
    ///
    /// # Long Polling (RPC-Level Only)
    ///
    /// If `wait_seconds` is provided and receive returns empty:
    /// - RPC layer subscribes to `notice://{realm}/{area}/{resource}/available`
    /// - Waits up to `wait_seconds` for a notice or timeout
    /// - Retries receive on notice or timeout
    /// - QueueActor NEVER blocks or stores waiters
    /// - Notices are hints (at-most-once, no guarantee of message availability)
    Receive {
        family_id: RouteFamily,
        route: Route,
        lease_seconds: u64,
        batch_size: Option<usize>,
        wait_seconds: Option<u64>,
    },

    /// Extend message lease
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/extend`
    ///
    /// Extends the expiration time for a reserved message.
    /// Requires valid token. Fails if token mismatches or lease expired.
    Extend {
        family_id: RouteFamily,
        route: Route,
        id: MessageId,
        token: u64,
        lease_seconds: u64,
    },

    /// Acknowledge message processing
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/ack`
    ///
    /// Marks message as successfully processed and acknowledges delivery.
    /// Removes inflight entry and deletes durable record.
    /// Requires valid token. Fails if token mismatches or lease expired.
    Ack {
        family_id: RouteFamily,
        route: Route,
        id: MessageId,
        token: u64,
    },

    /// Subscribe to queue availability notifications
    ///
    /// Registers a subscription for notifications when the queue transitions
    /// from empty to non-empty state. Notifications are debounced (25ms) and
    /// lightweight (no message data included).
    ///
    /// The server publishes notifications to `{route}/available` which matches
    /// subscriptions to the base route via wildcard pattern matching.
    Subscribe {
        family_id: RouteFamily,
        pattern: Route,
        session_id: u64,
        subscriber: crate::runtime::routing::RouteAddress,
    },

    /// Unsubscribe from queue availability notifications
    ///
    /// Removes a specific subscription identified by pattern and session.
    Unsubscribe {
        family_id: RouteFamily,
        pattern: Route,
        session_id: u64,
        subscriber: crate::runtime::routing::RouteAddress,
    },

    /// Unsubscribe all queue subscriptions for a session
    ///
    /// Called on session disconnect to cleanup all subscriptions.
    UnsubscribeAll {
        session_id: u64,
        subscriber: crate::runtime::routing::RouteAddress,
    },

    /// Internal timer expiration event
    ///
    /// Not exposed via external routes.
    /// Sent by the actor's timer system when a lease expires.
    /// Causes message to be re-enqueued to the ready queue.
    LeaseExpired { id: MessageId },
}

/// Queue errors
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QueueError {
    /// Invalid realm format (3010)
    InvalidRealm,

    /// Realm mismatch - operation targets different realm than active subscription (3011)
    RealmMismatch,
}

impl QueueError {
    pub fn code(&self) -> u16 {
        match self {
            QueueError::InvalidRealm => 3010,
            QueueError::RealmMismatch => 3011,
        }
    }
}

/// Queue operation responses
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum QueueResponse {
    /// Message successfully sent
    Sent { id: MessageId },

    /// Multiple messages successfully sent in one batch (same semantics as N×Sent)
    SentBatch { ids: Vec<MessageId> },

    /// Messages successfully received
    Received { messages: Vec<ReservedMessage> },

    /// Lease successfully extended
    Extended,

    /// Message successfully acknowledged
    Acked,

    /// Subscription successfully registered
    SubscribeOk { subscription_id: u64 },

    /// Subscription successfully removed
    UnsubscribeOk,

    /// Invalid token (mismatch with expected value)
    InvalidToken,

    /// Lease already expired before operation
    LeaseExpired,

    /// Message not found (completed or never existed)
    NotFound,

    /// Bad request (malformed parameters)
    BadRequest { reason: String },

    /// Queue does not exist
    QueueNotFound,

    /// Internal error
    Error { message: String },
}
