//! Queue protocol message types and responses
//!
//! Defines the message types for queue operations:
//! - **Enqueue**: Add message to queue
//! - **Reserve**: Lease one or more messages for processing
//! - **Extend**: Extend lease expiration for a reserved message
//! - **Complete**: Mark message as processed and delete it
//!
//! # Queue Identity
//!
//! Queues are uniquely identified by (RouteFamily, realm, area, resource):
//! - RouteFamily: Routing isolation boundary (opaque u64)
//! - realm/area/resource: Logical identity within the family
//!
//! # Lease Semantics
//!
//! - Messages are reserved with a lease duration
//! - While leased, messages are invisible to other consumers
//! - Leases expire automatically, returning messages to the ready queue
//! - Redelivered messages have incremented attempt counters
//!
//! # Token Protocol
//!
//! - Each reserved message gets a random u64 token
//! - Tokens must be provided for extend/complete operations
//! - Invalid tokens are rejected (prevents accidental duplicate operations)
//! - Tokens are ephemeral (not persisted, regenerated on actor restart)
//!
//! # Long Polling (RPC-Level Only)
//!
//! Reserve operations support optional long polling via `wait_seconds`:
//! - QueueActor always returns immediately (never blocks)
//! - If empty and `wait_seconds > 0`, RPC layer:
//!   1. Subscribes to `notice://{realm}/{area}/{resource}/available`
//!   2. Waits up to `wait_seconds` for a notice or timeout
//!   3. Retries reserve on notice or timeout
//! - Notices are hints (at-most-once), not guarantees
//! - QueueActor never stores waiters or blocking state

use crate::runtime::routing::{Route, RouteFamily};
use bytes::Bytes;

/// Parsed queue identity
///
/// Queues are uniquely identified by (RouteFamily, realm, area, resource):
/// - RouteFamily: Routing isolation boundary (opaque u64)
/// - realm/area/resource: Logical identity within the family
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct QueueKey {
    pub family: RouteFamily,
    pub realm: String,
    pub area: String,
    pub resource: String,
}

impl QueueKey {
    /// Parse a route into queue key
    ///
    /// Expected route format: `{scheme}://{realm}/{area}/{resource}/{operation}`
    /// or `/{realm}/{area}/{resource}/{operation}`
    ///
    /// Returns None if the route doesn't match the expected format.
    pub fn from_route(family: RouteFamily, route: &Route) -> Option<Self> {
        let path = route.as_str();

        // Strip scheme if present (e.g., "queue://..." → "...")
        let path_without_scheme = if let Some(pos) = path.find("://") {
            &path[pos + 3..]
        } else {
            path
        };

        let parts: Vec<&str> = path_without_scheme
            .trim_start_matches('/')
            .split('/')
            .collect();

        if parts.len() >= 4 {
            Some(QueueKey {
                family,
                realm: parts[0].to_string(),
                area: parts[1].to_string(),
                resource: parts[2].to_string(),
            })
        } else {
            None
        }
    }
}

/// Message identifier
///
/// Opaque u64 identifier for messages in the queue.
/// Generated by the actor and used for all subsequent operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageId(u64);

impl MessageId {
    /// Create a new message ID from a u64
    pub fn new(id: u64) -> Self {
        Self(id)
    }

    /// Get the underlying u64 value
    pub fn as_u64(&self) -> u64 {
        self.0
    }
}

impl std::fmt::Display for MessageId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Reserved message with body and lease metadata
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReservedMessage {
    /// Message identifier
    pub id: MessageId,

    /// Message body
    pub body: Bytes,

    /// Lease token (required for extend/complete)
    pub token: u64,

    /// Lease duration in seconds
    pub lease_seconds: u64,

    /// Number of delivery attempts (starts at 1)
    pub attempts: u32,
}

/// Queue domain messages
///
/// All queue operations are asynchronous and return responses via
/// the actor messaging system.
#[derive(Debug, Clone)]
pub enum QueueMessage {
    /// Enqueue a message
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/enqueue`
    ///
    /// Writes the message body to durable storage and adds it to the ready queue.
    /// If delay_seconds is provided, message won't be visible until delay elapses.
    /// Returns the MessageId for tracking.
    Enqueue {
        family_id: RouteFamily,
        route: Route,
        body: Bytes,
        delay_seconds: Option<u64>,
    },

    /// Enqueue a batch of messages (first-class batch API)
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/enqueue_batch`
    ///
    /// Writes all messages in ONE Midge write batch for amortized cost.
    /// Preserves FIFO ordering within the batch.
    /// Returns MessageIds in the same order as input.
    ///
    /// # Semantics
    /// - Exactly ONE Midge write batch per enqueue_batch call
    /// - All messages succeed or all fail (no partial visibility)
    /// - delay_seconds applies to all messages if scalar, or per-message if Vec
    /// - At most ONE availability notice per batch
    ///
    /// # Performance
    /// - Optimized for high-throughput ingestion (1M+ msg/sec)
    /// - Amortizes durable write cost across batch
    /// - Minimal per-message overhead
    EnqueueBatch {
        family_id: RouteFamily,
        route: Route,
        messages: Vec<Bytes>,
        delay_seconds: Option<u64>, // Scalar: apply to all messages
    },

    /// Reserve messages for processing
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/reserve`
    ///
    /// Pops up to `batch_size` messages from the ready queue, creates leases,
    /// and returns them with bodies loaded from storage.
    ///
    /// If `batch_size` is None, defaults to 1.
    ///
    /// # Long Polling (RPC-Level Only)
    ///
    /// If `wait_seconds` is provided and reserve returns empty:
    /// - RPC layer subscribes to `notice://{realm}/{area}/{resource}/available`
    /// - Waits up to `wait_seconds` for a notice or timeout
    /// - Retries reserve on notice or timeout
    /// - QueueActor NEVER blocks or stores waiters
    /// - Notices are hints (at-most-once, no guarantee of message availability)
    Reserve {
        family_id: RouteFamily,
        route: Route,
        lease_seconds: u64,
        batch_size: Option<usize>,
        wait_seconds: Option<u64>,
    },

    /// Extend message lease
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/extend`
    ///
    /// Extends the expiration time for a reserved message.
    /// Requires valid token. Fails if token mismatches or lease expired.
    Extend {
        family_id: RouteFamily,
        route: Route,
        id: MessageId,
        token: u64,
        lease_seconds: u64,
    },

    /// Complete message processing
    ///
    /// Route format: `queue://{realm}/{area}/{resource}/complete`
    ///
    /// Marks message as successfully processed.
    /// Removes inflight entry and deletes durable record.
    /// Requires valid token. Fails if token mismatches or lease expired.
    Complete {
        family_id: RouteFamily,
        route: Route,
        id: MessageId,
        token: u64,
    },

    /// Internal timer expiration event
    ///
    /// Not exposed via external routes.
    /// Sent by the actor's timer system when a lease expires.
    /// Causes message to be re-enqueued to the ready queue.
    LeaseExpired { id: MessageId },
}

/// Queue operation responses
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum QueueResponse {
    /// Message successfully enqueued
    Enqueued { id: MessageId },

    /// Batch of messages successfully enqueued
    EnqueuedBatch { ids: Vec<MessageId> },

    /// Messages successfully reserved
    Reserved { messages: Vec<ReservedMessage> },

    /// Lease successfully extended
    Extended,

    /// Message successfully completed
    Completed,

    /// Invalid token (mismatch with expected value)
    InvalidToken,

    /// Lease already expired before operation
    LeaseExpired,

    /// Message not found (completed or never existed)
    NotFound,

    /// Bad request (malformed parameters)
    BadRequest { reason: String },

    /// Queue does not exist
    QueueNotFound,

    /// Internal error
    Error { message: String },
}
