name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update Rust
        run: rustup update

      - name: Install Rust components
        run: rustup component add rustfmt clippy

      - name: Install cntryl-tools
        run: cargo install --git https://github.com/cntryl/tools

      - name: Cargo fmt check
        run: cargo fmt --all -- --check

      - name: Validate test conventions
        run: cntryl-tools validate-tests

      - name: Cargo clippy pedantic
        run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings -D clippy::pedantic

      - name: Cargo build
        run: cargo build --locked

      - name: Cargo bench compile
        run: cargo bench --locked --no-run

      - name: Cargo test compile
        run: cargo test --locked --no-run

      - name: Cargo test
        run: cargo test --locked
