// Shared drivers and measurement support for saturation and endurance campaigns.
mod artifacts;
mod durable;
mod ephemeral;
mod fixture;
mod histogram;
mod runner;
mod types;

pub(crate) use runner::run;
pub(crate) use types::Domain;

pub(crate) fn main() {
    // Initialize before the framework starts threads. Explicit CLI/environment
    // settings still take precedence over these owned-window defaults.
    for (key, value) in [
        ("STRESS_PROFILE", "smoke"),
        ("STRESS_SAMPLES", "1"),
        ("STRESS_WARMUP_SAMPLES", "0"),
        ("STRESS_COOLDOWN_SAMPLES", "0"),
        ("STRESS_NO_PROGRESS_TIMEOUT_SECS", "60"),
        ("STRESS_TIMEOUT_SECS", "4500"),
    ] {
        if std::env::var_os(key).is_none() {
            std::env::set_var(key, value);
        }
    }
    // Use the same entry point generated by cntryl_stress::stress_main!().
    cntryl_stress::__private::stress_binary_main();
}
